apiVersion: v1
kind: Pod   
metadata:
  generateName: bert-
  namespace: iadeep
  labels:
    app: bert
spec:
  containers:
    - name: share-gpu-bert
      image: 10.119.46.41:30003/library/iadeep_benchmarks:1.0
      imagePullPolicy: Always
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  
      command:
        - python
      args: ["/workspace/workloads/job_agent.py", "--job_name=bert", "--batch_size=8"]
      resources:
        requests:
          cpu: 2
          memory: 20G
          gpushare/gpu-mem: 11
        limits:
          cpu: 2
          memory: 20G
          gpushare/gpu-mem: 11
      volumeMounts:
      - name: datapath
        mountPath: /workspace/dataset/
        readOnly: True
      - name: logpath   
        mountPath: /workspace/workloads/result/
        readOnly: False
      - name: cachepath
        mountPath: /root/.cache/
        readOnly: True
      ports:
        - containerPort: 80
  volumes:
  - name: datapath
    hostPath:
      path: /nfs/dataset/
      type: DirectoryOrCreate
  - name: logpath
    hostPath:
      path: /nfs/logs/
      type: DirectoryOrCreate
  - name: cachepath
    hostPath:
      path: /nfs/cache
      type: DirectoryOrCreate

  nodeSelector:
    kubernetes.io/hostname: slave3
    gpushare: "true"
  restartPolicy: Never
  schedulerName: iadeep-scheduler
