apiVersion: v1
kind: Pod   
metadata:
  generateName: neumf-
  namespace: iadeep
  labels:
    app: neumf
spec:
  containers:
    - name: share-gpu-neumf
      image: www.myharbor.com/library/iadeep_benchmarks:1.0
      imagePullPolicy: Always
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  
      command:
        - python
      args: ["/workspace/workloads/job_agent.py", "--job_name=ncf/neumf", "--batch_size=1024"]
      resources:
        requests:
          cpu: 2
          memory: 10G
          gpushare/gpu-mem: 3
        limits:
          cpu: 2
          memory: 10G
          gpushare/gpu-mem: 3
      volumeMounts:
      - name: datapath
        mountPath: /workspace/dataset/
        readOnly: False
      - name: logpath   
        mountPath: /workspace/workloads/result/
        readOnly: False
      - name: cachepath
        mountPath: /workspace/cache/
        readOnly: False
      ports:
        - containerPort: 80
  volumes:
  - name: datapath
    hostPath:
      path: /nfs/dataset/
      type: DirectoryOrCreate
  - name: logpath
    hostPath:
      path: /nfs/logs/
      type: DirectoryOrCreate
  - name: cachepath
    hostPath:
      path: /nfs/cache
      type: DirectoryOrCreate

  nodeSelector:
    # kubernetes.io/hostname: slave12
    gpushare: "true"
  restartPolicy: Never
  schedulerName: iadeep-scheduler
